export type { RawComment, LearnedLesson } from './types';
export { listPrs, fetchCommentsForPr, groupThreads } from './github';
export type { PrRef } from './github';
export { isSubstantive, categorize } from './classify';
export { outcomeFor } from './outcome';
export { isOutdated } from './github';
export { greedyCluster, centroid, adaptiveCosineThreshold } from './cluster';
export { distilledPitfallId } from './distill';
export type { ClusterInput } from './distill';
export { scanHistory } from './pipeline';
export type { DistillOptions, ScanResult } from './pipeline';
